[package]
name = "tail"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.17", features = ["derive"] }
confy = "0.6.1"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.125"
ureq = { version = "2.10.0", features = ["json"] }
